-- MySQL Script generated by MySQL Workbench
-- Wed Jan 31 16:19:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spring_security
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spring_security` ;

-- -----------------------------------------------------
-- Schema spring_security
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spring_security` DEFAULT CHARACTER SET utf8 ;
USE `spring_security` ;

-- -----------------------------------------------------
-- Table `spring_security`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_security`.`user` (
  `id` BIGINT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_security`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_security`.`role` (
  `id` BIGINT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_security`.`access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_security`.`access` (
  `id` BIGINT UNSIGNED NULL AUTO_INCREMENT,
  `fid` BIGINT NULL DEFAULT 1,
  `module` VARCHAR(45) NULL DEFAULT 'api',
  `controller` VARCHAR(45) NULL DEFAULT '*',
  `function` VARCHAR(45) NULL DEFAULT '*',
  `creatAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_security`.`role_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_security`.`role_access` (
  `id` BIGINT UNSIGNED NULL AUTO_INCREMENT,
  `roleId` BIGINT UNSIGNED NOT NULL,
  `accessId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_security`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_security`.`user_role` (
  `id` BIGINT UNSIGNED NULL AUTO_INCREMENT,
  `userId` BIGINT UNSIGNED NOT NULL,
  `roleId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
